# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e25cb375fb1dcd12265a1f9fa093274464e1e802d47aba93d9765722c2a8c3189aa03580ce57982d323d27570a9ac2fd05e7164e23496fb2e690e2539302029

test:
  secret_key_base: e287c9d3ada93d2dcbbe3b471e9564b7c3741ebf5f1ecc1f05ff4bc41ecaaa1a544fbe6c512a1e95bad43b3ae3717abfa01510e5e15539267d996816cafa095f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
